name: CI / CD Pipeline
on:
  workflow_dispatch:

jobs:
  RunJiraPreDeploymentSetup:
    runs-on: ubuntu-latest
    steps:
    - name: Runs Pre Deployment Setup
      uses: actions/defaultJiraPredeploymentsetup@v2
      
