name: CI / CD Pipeline
on:
  workflow_dispatch:

jobs:
  RunJiraPreDeploymentSetup:
    runs-on: ubuntu-latest
    steps:
    - name: Runs Pre Deployment Setup
      uses: BalrajBemainboina/ActionSharedLibrary/jirapredeployment@main
  
  JiraDeployment:
    runs-on: ubuntu-latest
    needs: [RunJiraPreDeploymentSetup]
    steps:
    - name: Jira Deployment
      uses: BalrajBemainboina/ActionSharedLibrary/jiradeployment@main
   
      
      
